# Generated by Django 5.2 on 2025-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavail',
            name='campaingn_description',
            field=models.TextField(blank=True),
        ),
    ]
