# Generated by Django 5.2 on 2025-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0002_serviceavail_campaingn_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavail',
            name='web_img',
            field=models.FileField(blank=True, upload_to='web_images/'),
        ),
    ]
