# Generated by Django 5.2 on 2025-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0003_serviceavail_web_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavail',
            name='height',
            field=models.IntegerField(default=1.6),
        ),
        migrations.AddField(
            model_name='serviceavail',
            name='width',
            field=models.IntegerField(default=1),
        ),
    ]
