# Generated by Django 5.2 on 2025-05-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0004_serviceavail_height_serviceavail_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavail',
            name='redirect_url',
            field=models.URLField(default='https://aliveframe.com/'),
        ),
    ]
