# Generated by Django 5.2 on 2025-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0005_serviceavail_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceavail',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='serviceavail',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=4),
        ),
    ]
