# Generated by Django 5.2 on 2025-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0006_alter_serviceavail_height_alter_serviceavail_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceavail',
            old_name='web_img',
            new_name='reference_img',
        ),
        migrations.AddField(
            model_name='serviceavail',
            name='campaign_name',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceavail',
            name='target_img',
            field=models.FileField(blank=True, upload_to='web_images/'),
        ),
    ]
