# Generated by Django 5.2 on 2025-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0007_rename_web_img_serviceavail_reference_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceavail',
            name='web_video',
        ),
        migrations.AddField(
            model_name='serviceavail',
            name='overlap_video',
            field=models.FileField(default=1, upload_to='overlap_videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceavail',
            name='reference_img',
            field=models.FileField(blank=True, upload_to='reference_images/'),
        ),
        migrations.AlterField(
            model_name='serviceavail',
            name='target_img',
            field=models.FileField(blank=True, upload_to='target_images/'),
        ),
    ]
