# Generated by Django 5.2 on 2025-05-09 13:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0008_remove_serviceavail_web_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceavail',
            name='campaign_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceid', to='arapp.serviceavail')),
            ],
        ),
    ]
