# Generated by Django 5.2 on 2026-01-13 12:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0009_serviceavail_campaign_days_servicestatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=15)),
                ('logo', models.ImageField(upload_to='burger_logo_images/')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='BurgerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameid', to='arapp.burgergame')),
            ],
        ),
    ]
