# Generated by Django 5.2 on 2026-01-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0010_burgergame_burgerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgergame',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='burgergame',
            name='lon',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
