# Generated by Django 5.2 on 2026-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0011_alter_burgergame_lat_alter_burgergame_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgergame',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='burgergame',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='models/glb/'),
        ),
    ]
