# Generated by Django 5.2 on 2026-02-15 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0012_burgergame_enabled_burgergame_glb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('max_size', models.DecimalField(decimal_places=20, max_digits=50)),
                ('min_size', models.DecimalField(decimal_places=20, max_digits=50)),
                ('min_distance', models.DecimalField(decimal_places=20, max_digits=50)),
                ('max_distance', models.DecimalField(decimal_places=20, max_digits=50)),
                ('logo', models.ImageField(upload_to='burger_logo_images/')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('glb_file', models.FileField(blank=True, null=True, upload_to='models/glb/')),
                ('video_file', models.FileField(upload_to='product_videos/')),
                ('fixed_value', models.IntegerField(default=2)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
