# Generated by Django 5.2 on 2026-02-15 21:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0013_argame'),
    ]

    operations = [
        migrations.AddField(
            model_name='argame',
            name='website_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ArGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argameid', to='arapp.argame')),
            ],
        ),
    ]
