# Generated by Django 5.2 on 2026-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0014_argame_website_url_argamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argamescore',
            name='player_name',
            field=models.CharField(max_length=10),
        ),
    ]
