# Generated by Django 5.2 on 2026-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0015_alter_argamescore_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='argamescore',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
