# Generated by Django 5.2 on 2026-04-06 11:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0017_argame_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='argamescore',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ThreeDClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('business_size', models.CharField(max_length=255)),
                ('business_industry', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pin_code', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ARExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_file', models.FileField(upload_to='markettingasset/targets/')),
                ('model_3d', models.FileField(upload_to='markettingasset/models/')),
                ('reference_image', models.FileField(upload_to='markettingasset/reference_images/')),
                ('scale_x', models.FloatField(default=0.25)),
                ('scale_y', models.FloatField(default=0.25)),
                ('scale_z', models.FloatField(default=0.25)),
                ('rot_x', models.FloatField(default=0)),
                ('rot_y', models.FloatField(default=90)),
                ('rot_z', models.FloatField(default=90)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_experiences', to='arapp.threedclientprofile')),
            ],
        ),
    ]
