# Generated by Django 5.2 on 2026-05-15 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0018_alter_argamescore_timestamp_threedclientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatistics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
