# Generated by Django 5.2 on 2025-08-10 10:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pin_code', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FrameCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_count', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientid', to='photo_frame.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FramePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=30)),
                ('razorpay_order_id', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('paid_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientassid', to='photo_frame.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FrameUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='photo_frame.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MediaForWebExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_video', models.FileField(upload_to='web_videos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameuser', to='photo_frame.frameuserinfo')),
            ],
        ),
    ]
