# Generated by Django 5.2 on 2025-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1.6, max_digits=4),
        ),
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='reference_img',
            field=models.FileField(blank=True, upload_to='photo_frame_reference_images/'),
        ),
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='target_img',
            field=models.FileField(blank=True, upload_to='photo_frame_target_images/'),
        ),
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=4),
        ),
        migrations.AlterField(
            model_name='mediaforwebexperience',
            name='web_video',
            field=models.FileField(upload_to='photo_frame_videos/'),
        ),
    ]
