# Generated by Django 5.2 on 2025-08-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0002_mediaforwebexperience_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='state',
        ),
    ]
