# Generated by Django 5.2 on 2025-08-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0003_remove_frameuserinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameuserinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='frameuserinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='mediaforwebexperience',
            name='reference_img',
            field=models.FileField(upload_to='photo_frame_reference_images/'),
        ),
    ]
