# Generated by Django 5.2 on 2025-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0004_alter_frameuserinfo_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='type',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square')], default='square', max_length=10),
        ),
    ]
