# Generated by Django 5.2 on 2025-12-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0005_mediaforwebexperience_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaforwebexperience',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mediaforwebexperience',
            name='type',
            field=models.CharField(choices=[('circle', 'Circle'), ('square', 'Square'), ('album', 'Album')], default='square', max_length=10),
        ),
    ]
