# Generated by Django 5.2 on 2025-12-01 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_frame', '0006_alter_mediaforwebexperience_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='frameuserinfo',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
